---
name: Build Custom RPM
description: Build a custom RPM on different distributions.
author: Shadow Walker <me@buluma.me.ke>

inputs:
  distribution:
    description: The distribution to run the build on.
    required: false
    default: centos-7

runs:
  using: docker
  image: 'docker://buluma/github-action-rpmbuild

branding:
  icon: box
  color: green
